### Import train station data and transform by NJ municipality


key = 'AIzaSyDW2X9d_T7NM4HBj3VsXsKTbJKCfgRBDCw'

In [48]:
import pandas as pd
import urllib.request
import requests
import json
from pprint import pprint
from http.client import HTTPResponse

In [134]:
stops = pd.read_csv('Data/stops.txt')
stops.info()
stops.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 7 columns):
stop_id      229 non-null int64
stop_code    229 non-null int64
stop_name    229 non-null object
stop_desc    0 non-null float64
stop_lat     229 non-null float64
stop_lon     229 non-null float64
zone_id      229 non-null int64
dtypes: float64(3), int64(3), object(1)
memory usage: 12.6+ KB

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id
0,1,95001,30TH ST. PHL.,NaN,39.956565,-75.182327,5961
1,2,95002,ABSECON,NaN,39.424333,-74.502094,333
2,3,95003,ALLENDALE,NaN,41.030902,-74.130957,2893
3,4,95004,ALLENHURST,NaN,40.237659,-74.006769,5453
4,5,95005,ANDERSON STREET,NaN,40.894458,-74.043781,1357
5,6,95006,ANNANDALE,NaN,40.645173,-74.878569,5197
6,8,95008,ASBURY PARK,NaN,40.215359,-74.014786,5453
7,9,95009,ATCO,NaN,39.783547,-74.907588,4429
8,10,95010,ATLANTIC CITY,NaN,39.363299,-74.441486,77
9,11,95011,AVENEL,NaN,40.577620,-74.277530,2381
10,12,95012,BASKING RIDGE,NaN,40.711378,-74.555270,4173
11,13,95013,BAY HEAD,NaN,40.077178,-74.046183,5965
12,14,95014,BAY STREET,NaN,40.808178,-74.208681,1357
13,15,95015,BELMAR,NaN,40.180590,-74.027301,5709
14,17,95017,BERKELEY HEIGHTS,NaN,40.682345,-74.442649,2893
15,18,95018,BERNARDSVILLE,NaN,40.716845,-74.571023,4173
16,19,95019,BLOOMFIELD,NaN,40.792709,-74.200043,1101
17,20,95020,BOONTON,NaN,40.903378,-74.407736,3661
18,21,95021,BOUND BROOK,NaN,40.560929,-74.530617,3661
19,22,95022,BRADLEY BEACH,NaN,40.203751,-74.018891,5453
20,23,95023,BRICK CHURCH,NaN,40.765134,-74.218612,1101
21,24,95024,BRIDGEWATER,NaN,40.559906,-74.551741,3917
22,25,95025,BROADWAY,NaN,40.922505,-74.115236,1613
23,26,95026,CAMPBELL HALL,NaN,41.450917,-74.266554,5709
24,27,95027,CHATHAM,NaN,40.740137,-74.384812,2637
25,28,95028,CHERRY HILL,NaN,39.928447,-75.041661,5197
26,29,95029,CLIFTON,NaN,40.867998,-74.153203,1357
27,30,95030,CONVENT,NaN,40.779040,-74.443435,3149
28,31,95031,ROSELLE PARK,NaN,40.667152,-74.266320,1613
29,32,95032,CRANFORD,NaN,40.655523,-74.303226,1869
30,33,95033,DELAWANNA,NaN,40.831369,-74.131262,845
31,34,95034,DENVILLE,NaN,40.883900,-74.481513,4173
32,35,95035,DOVER,NaN,40.883415,-74.555887,4429
33,36,95036,DUNELLEN,NaN,40.590869,-74.463043,3149
34,37,95037,EAST ORANGE,NaN,40.760977,-74.210464,1101
35,38,95038,EDISON STATION,NaN,40.519148,-74.410972,3405
36,39,95039,EGG HARBOR,NaN,39.526441,-74.648028,1613
37,40,95040,ELBERON,NaN,40.265292,-73.997620,5197
38,41,95041,ELIZABETH,NaN,40.667857,-74.215174,1357
39,42,95042,EMERSON,NaN,40.975036,-74.027471,2125
40,43,95043,ESSEX STREET,NaN,40.878973,-74.051893,1357
41,44,95044,FANWOOD,NaN,40.641060,-74.385003,2381
42,45,95045,FAR HILLS,NaN,40.685712,-74.633734,4429
43,46,95046,GARFIELD,NaN,40.866669,-74.105560,1101
44,47,95047,GARWOOD,NaN,40.652569,-74.324794,2125
45,48,95048,GILLETTE,NaN,40.678253,-74.468317,3149
46,49,95049,GLADSTONE,NaN,40.720284,-74.666371,4685
47,50,95050,GLEN RIDGE,NaN,40.800590,-74.204655,1101
48,51,95051,GLEN ROCK BORO HALL,NaN,40.961370,-74.129300,2125
49,52,95052,GLEN ROCK MAIN LINE,NaN,40.962206,-74.133485,2125

In [11]:
latlng = []
for i in range(len(stops)):
    latlng.append(str(stops['stop_lat'][i])+','+str(stops['stop_lon'][i]))

In [60]:
latlng[:20]

['39.956565,-75.182327',
 '39.424333,-74.502094',
 '41.030902,-74.130957',
 '40.237659,-74.006769',
 '40.894458,-74.043781',
 '40.645173,-74.878569',
 '40.215359,-74.014786',
 '39.783547,-74.907588',
 '39.363299,-74.441486',
 '40.57762,-74.27753',
 '40.711378,-74.55527',
 '40.077178,-74.046183',
 '40.808178,-74.208681',
 '40.18059,-74.027301',
 '40.682345,-74.442649',
 '40.716845,-74.571023',
 '40.792709,-74.200043',
 '40.903378,-74.407736',
 '40.560929,-74.530617',
 '40.203751,-74.018891']

In [44]:
starturl = 'https://maps.googleapis.com/maps/api/geocode/json?latlng='

endurl = '&result_type=administrative_area_level_2|locality&key=AIzaSyDW2X9d_T7NM4HBj3VsXsKTbJKCfgRBDCw'

In [66]:
towns = []
munis = []
counties = []
for place in latlng:
    url = starturl+place+endurl
    response = requests.get(url)
    towns.append(response.json()['results'][0]['address_components'][0]['long_name'])
    munis.append(response.json()['results'][0]['address_components'][0]['short_name'])
    counties.append(response.json()['results'][0]['address_components'][1]['long_name'])

In [110]:
df = pd.DataFrame([towns,munis,counties]).T
df.columns = ['towns','munis','counties']
df['lower_town'] = [town.lower() for town in df['towns']]
df['vals'] = [1]*len(df)
#counties
df.head(30)

,towns,munis,counties,lower_town,vals
0,Philadelphia,Philadelphia,Philadelphia County,philadelphia,1
1,Absecon,Absecon,Atlantic County,absecon,1
2,Allendale,Allendale,Bergen County,allendale,1
3,Allenhurst,Allenhurst,Monmouth County,allenhurst,1
4,Hackensack,Hackensack,Bergen County,hackensack,1
5,Hunterdon County,Hunterdon County,New Jersey,hunterdon county,1
6,Asbury Park,Asbury Park,Monmouth County,asbury park,1
7,Waterford,Waterford,Winslow Township,waterford,1
8,Atlantic City,Atlantic City,Atlantic County,atlantic city,1
9,Woodbridge Township,Woodbridge Township,Middlesex County,woodbridge township,1
10,Bernards,Bernards,Somerset County,bernards,1
11,Bay Head,Bay Head,Ocean County,bay head,1
12,Montclair,Montclair,Essex County,montclair,1
13,Belmar,Belmar,Monmouth County,belmar,1
14,Berkeley Heights,Berkeley Heights,Union County,berkeley heights,1
15,Bernardsville,Bernardsville,Somerset County,bernardsville,1
16,Essex County,Essex County,New Jersey,essex county,1
17,Boonton,Boonton,Morris County,boonton,1
18,Bound Brook,Bound Brook,Somerset County,bound brook,1
19,Bradley Beach,Bradley Beach,Monmouth County,bradley beach,1
20,East Orange,East Orange,Essex County,east orange,1
21,Bridgewater,Bridgewater,Somerset County,bridgewater,1
22,Fair Lawn,Fair Lawn,Bergen County,fair lawn,1
23,Campbell Hall,Campbell Hall,Hamptonburgh,campbell hall,1
24,Chatham,Chatham,Morris County,chatham,1
25,Cherry Hill,Cherry Hill,Camden County,cherry hill,1
26,Clifton,Clifton,Passaic County,clifton,1
27,Morris Township,Morris Twp,Morris County,morris township,1
28,Roselle Park,Roselle Park,Union County,roselle park,1
29,Cranford,Cranford,Union County,cranford,1

In [135]:
df['county'] = [county.lower() for county in df['counties']]
df['county'] = [county.replace(' county','') for county in df['county']]
df.head()

,towns,munis,counties,lower_town,vals,county
0,Philadelphia,Philadelphia,Philadelphia County,philadelphia,1,philadelphia
1,Absecon,Absecon,Atlantic County,absecon,1,atlantic
2,Allendale,Allendale,Bergen County,allendale,1,bergen
3,Allenhurst,Allenhurst,Monmouth County,allenhurst,1,monmouth
4,Hackensack,Hackensack,Bergen County,hackensack,1,bergen

In [129]:
trains = df.groupby(['towns','munis','county','lower_town']).count()
trains.reset_index(inplace=True, level=['towns','munis','county','lower_town'])
#trains['town_bare'] = trains['towns'].lower()
trains.columns

trains.sort_values(by='towns')

,towns,munis,county,lower_town,counties,vals
0,Absecon,Absecon,atlantic,absecon,1,1
1,Allendale,Allendale,bergen,allendale,1,1
2,Allenhurst,Allenhurst,monmouth,allenhurst,1,1
3,Asbury Park,Asbury Park,monmouth,asbury park,1,1
4,Atlantic City,Atlantic City,atlantic,atlantic city,1,1
5,Bay Head,Bay Head,ocean,bay head,1,1
6,Bayonne,Bayonne,hudson,bayonne,4,4
7,Beaverdam Lake-Salisbury Mills,Beaverdam Lake-Salisbury Mills,orange,beaverdam lake-salisbury mills,1,1
8,Belleville,Belleville,bloomfield,belleville,1,1
9,Belmar,Belmar,monmouth,belmar,1,1
10,Berkeley Heights,Berkeley Heights,union,berkeley heights,1,1
11,Bernards,Bernards,somerset,bernards,2,2
12,Bernardsville,Bernardsville,somerset,bernardsville,1,1
13,Beverly,Beverly,burlington,beverly,1,1
14,Boonton,Boonton,morris,boonton,1,1
15,Bordentown,Bordentown,falls township,bordentown,1,1
16,Bound Brook,Bound Brook,somerset,bound brook,1,1
17,Bradley Beach,Bradley Beach,monmouth,bradley beach,1,1
18,Branchburg,Branchburg,somerset,branchburg,1,1
19,Bridgewater,Bridgewater,somerset,bridgewater,1,1
20,Burlington,Burlington,bristol township,burlington,2,2
21,Camden,Camden,camden,camden,4,4
22,Campbell Hall,Campbell Hall,hamptonburgh,campbell hall,1,1
23,Chatham,Chatham,morris,chatham,1,1
24,Cherry Hill,Cherry Hill,camden,cherry hill,1,1
25,Cinnaminson,Cinnaminson,burlington,cinnaminson,1,1
26,City of Orange,City of Orange,essex,city of orange,2,2
27,Clifton,Clifton,passaic,clifton,2,2
28,Cranford,Cranford,union,cranford,1,1
29,Delanco,Delanco,bensalem township,delanco,1,1
...,...,...,...,...,...,...
112,River Edge,River Edge,bergen,river edge,2,2
113,Riverside,Riverside,bensalem township,riverside,1,1
114,Riverton,Riverton,burlington,riverton,1,1
115,Roselle Park,Roselle Park,union,roselle park,1,1
116,Roxbury Township,Roxbury Township,morris,roxbury township,2,2
117,Scotchtown,Scotchtown,wallkill,scotchtown,1,1
118,Secaucus,Secaucus,hudson,secaucus,2,2
119,Sloatsburg,Sloatsburg,ramapo,sloatsburg,1,1
120,Somerset County,Somerset County,new jersey,somerset county,2,2
121,Somerville,Somerville,somerset,somerville,1,1
122,South Amboy,South Amboy,middlesex,south amboy,1,1
123,South Orange,South Orange,essex,south orange,2,2
124,Spring Lake Heights,Spring Lake Heights,ocean township,spring lake heights,1,1
125,Spring Valley,Spring Valley,ramapo,spring valley,1,1
126,Suffern,Suffern,ramapo,suffern,1,1
127,Summit,Summit,union,summit,1,1
128,Trenton,Trenton,lower makefield township,trenton,4,4
129,Union,Union,union,union,1,1
130,Union City,Union City,hudson,union city,1,1
131,Waldwick,Waldwick,bergen,waldwick,1,1
132,Waterford,Waterford,winslow township,waterford,1,1
133,Wayne,Wayne,passaic,wayne,2,2
134,Weehawken,Weehawken,hudson,weehawken,2,2
135,West Windsor Township,West Windsor Township,plainsboro township,west windsor township,1,1
136,Westfield,Westfield,union,westfield,1,1
137,Westwood,Westwood,bergen,westwood,1,1
138,Wood-Ridge,Wood-Ridge,bergen,wood-ridge,2,2
139,Woodbridge Township,Woodbridge Township,middlesex,woodbridge township,3,3
140,Woodbury,Woodbury,woodbury,woodbury,1,1
141,Woodcliff Lake,Woodcliff Lake,bergen,woodcliff lake,1,1

In [45]:
source = starturl+latlng[10]+endurl
source

'https://maps.googleapis.com/maps/api/geocode/json?latlng=40.711378,-74.55527&result_type=administrative_area_level_2|locality&key=AIzaSyDW2X9d_T7NM4HBj3VsXsKTbJKCfgRBDCw'

In [46]:
import requests
response = requests.get(source)
response.headers['content-type']

'application/json; charset=UTF-8'

In [58]:
response.json()['results'][0]['address_components'][0]['long_name']

'Bernards'

In [51]:
type(response.json())

dict

In [79]:
muni_names = pd.read_pickle('muni_names.pkl')

In [95]:
t =[muni.replace(' twp','') for muni in muni_names['town'] ]
t =[muni.replace(' boro','') for muni in t ]
t =[muni.replace(' city','') for muni in t ]
t =[muni.replace('jersey','jersey city') for muni in t ]
t

['washington',
 'riverside',
 'manchester',
 'toms river',
 'brick',
 'farmingdale',
 'neptune',
 'upper freehold',
 'roosevelt',
 'oceanport',
 'atlantic highlands',
 'south brunswick',
 'washington',
 'kearny town',
 'harmony',
 'washington',
 'north arlington',
 'secaucus town',
 'moonachie',
 'mansfield',
 'little ferry',
 'holmdel',
 'buena',
 'nutley',
 'shrewsbury',
 'tinton falls',
 'bay head',
 'newark',
 'jersey city',
 'wharton',
 'boonton town',
 'mount olive',
 'somers point',
 'voorhees',
 'seaside heights',
 'mount laurel',
 'cape may point',
 'rockleigh',
 'bellmawr',
 'winslow',
 'maple shade',
 'stratford',
 'lacey',
 'pemberton',
 'moorestown',
 'highland park',
 'monroe',
 'hazlet',
 'keansburg',
 'union beach',
 'alexandria',
 'bernardsville',
 'hoboken',
 'summit',
 'lebanon',
 'midland park',
 'wayne',
 'woodstown',
 'upper pittsgrove',
 'jackson',
 'lake como',
 'wood-ridge',
 'sea isle',
 'chesilhurst',
 'oldmans',
 'waterford',
 'woolwich',
 'bradley beach',
 'parsippany-troy hills',
 'alloway',
 'chester',
 'denville',
 'cape may',
 'north wildwood',
 'lower',
 'avalon',
 'middle',
 'longport',
 'upper',
 'corbin',
 'commercial',
 'downe',
 'lawrence',
 'atlantic',
 'greenwich',
 'vineland',
 'galloway',
 'elsinboro',
 'quinton',
 'hamilton',
 'elmer',
 'lakewood',
 'burlington',
 'surf',
 'mannington',
 'clayton',
 'long beach',
 'pilesgrove',
 'monroe',
 'south harrison',
 'glassboro',
 'mansfield',
 'pine valley',
 'mantua',
 'shamong',
 'logan',
 'gibbsboro',
 'gloucester',
 'greenwich',
 'paulsboro',
 'west deptford',
 'barrington',
 'haddon heights',
 'mount ephraim',
 'audubon park',
 'haddonfield',
 'woodland',
 'haddon',
 'north hanover',
 'fieldsboro',
 'chesterfield',
 'ocean gate',
 'berkeley',
 'lakehurst',
 'cinnaminson',
 'westampton',
 'beverly',
 'springfield',
 'bordentown',
 'avon-by-the-sea',
 'west windsor',
 'oradell',
 'haworth',
 'paramus',
 'closter',
 'emerson',
 'ridgewood village',
 'norwood',
 'allenhurst',
 'trenton',
 'howell',
 'robbinsville',
 'hamilton',
 'ocean',
 'hightstown',
 'jamesburg',
 'plainsboro',
 'helmetta',
 'princeton',
 'marlboro',
 'hopewell',
 'edison',
 'franklin',
 'green brook',
 'clark',
 'holland',
 'north plainfield',
 'linden',
 'watchung',
 'westwood',
 'carteret',
 'northvale',
 'pompton lakes',
 'old tappan',
 'river vale',
 'allendale',
 'sea bright',
 'spotswood',
 'woodcliff lake',
 'park ridge',
 'saddle river',
 'brigantine',
 'bridgeton',
 'woodbine',
 'dennis',
 'stockton',
 'east brunswick',
 'east amwell',
 'new brunswick',
 'hillsborough',
 'raritan',
 'piscataway',
 'roselle park',
 'warren',
 'scotch plains',
 'union',
 'high bridge',
 'pohatcong',
 'kenilworth',
 'clinton',
 'berkeley heights',
 'bayonne',
 'glen gardner',
 'springfield',
 'morristown town',
 'hampton',
 'far hills',
 'bedminster',
 'franklin',
 'guttenberg town',
 'livingston',
 'lyndhurst',
 'north bergen',
 'belvidere town',
 'mendham',
 'ocean',
 'caldwell',
 'edgewater',
 'montclair',
 'chester',
 'hanover',
 'carlstadt',
 'east hanover',
 'washington',
 'roxbury',
 'ridgefield park village',
 'white',
 'mount arlington',
 'lincoln park',
 'boonton',
 'montville',
 'pequannock',
 'riverdale',
 'butler',
 'kinnelon',
 'rockaway',
 'jefferson',
 'branchburg',
 'cedar grove',
 'hackettstown town',
 'knowlton',
 'hopatcong',
 'andover',
 'cresskill',
 'egg harbor',
 'liberty',
 'fairfield',
 'byram',
 'saddle brook',
 'totowa',
 'stanhope',
 'river edge',
 'new milford',
 'fair lawn',
 'demarest',
 'oakland',
 'montvale',
 'ramsey',
 'florham park',
 'ogdensburg',
 'mahwah',
 'walpack',
 'west milford',
 'teterboro',
 'mullica',
 'bernards',
 'wall',
 'aberdeen',
 'woodbridge',
 'stow creek',
 'fairfield',
 'maurice river',
 'millville',
 'sussex',
 'wantage',
 'montague',
 'neptune',
 'hillside',
 'newton town',
 'kingwood',
 'readington',
 'long hill',
 'chatham',
 'chatham',
 'mendham',
 'morris',
 'deerfield',
 'hopewell',
 'tuckerton',
 'pennsville',
 'elk',
 'carneys point',
 'camden',
 'southampton',
 'new hanover',
 'berlin',
 'medford',
 'cherry hill',
 'pennsauken',
 'hainesport',
 'florence',
 'west long branch',
 'eatontown',
 'long branch',
 'manalapan',
 'colts neck',
 'sayreville',
 'delaware',
 'lawrence',
 'perth amboy',
 'franklin',
 'metuchen',
 'hopewell',
 'west amwell',
 'keyport',
 'middletown',
 'elmwood park',
 'plainfield',
 'peapack-gladstone',
 'tewksbury',
 'dumont',
 'hammonton town',
 'wildwood',
 'bethlehem',
 'union',
 'millburn',
 'weehawken',
 'port republic',
 'lower alloways creek',
 'upper deerfield',
 'verona',
 'hackensack',
 'harrington park',
 'dover town',
 'bloomingdale',
 'pittsgrove',
 'hardwick',
 'lambertville',
 'barnegat light',
 'bass river',
 'little egg harbor',
 'ship bottom',
 'washington',
 'stafford',
 'hi-nella',
 'cliffside park',
 'pemberton',
 'point pleasant beach',
 'wildwood crest',
 'alpha',
 'east orange',
 'west orange',
 'sparta',
 'frenchtown',
 'bloomfield',
 'west cape may',
 'shiloh',
 'west wildwood',
 'frelinghuysen',
 'hillsdale',
 'point pleasant',
 'stone harbor',
 'burlington',
 'magnolia',
 'deptford',
 'margate',
 'folsom',
 'ventnor',
 'pine beach',
 'northfield',
 'weymouth',
 'linwood',
 'estell manor',
 'newfield',
 'east newark',
 'beach haven',
 'runnemede',
 'salem',
 'medford lakes',
 'buena vista',
 'tabernacle',
 'island heights',
 'franklin',
 'harvey cedars',
 'woodlynne',
 'pitman',
 'eagleswood',
 'edgewater park',
 'penns grove',
 'swedesboro',
 'harrison',
 'wenonah',
 'pine hill',
 'berlin',
 'fair haven',
 'beachwood',
 'clementon',
 'merchantville',
 'laurel springs',
 'east greenwich',
 'barnegat',
 'woodbury heights',
 'ocean',
 'lindenwold',
 'woodbury',
 'somerdale',
 'lawnside',
 'national park',
 'tavistock',
 'brooklawn',
 'rahway',
 'lavallette',
 'clinton town',
 'bridgewater',
 'westville',
 'wrightstown',
 'audubon',
 'lebanon',
 'delran',
 'garwood',
 'gloucester',
 'oaklyn',
 'califon',
 'monmouth beach',
 'collingswood',
 'seaside park',
 'south toms river',
 'lumberton',
 'mount holly',
 'palmyra',
 'delanco',
 'riverton',
 'eastampton',
 'mantoloking',
 'willingboro',
 'millstone',
 'brielle',
 'freehold',
 'east windsor',
 'plumsted',
 'englishtown',
 'interlaken',
 'sea girt',
 'pennington',
 'bordentown',
 'spring lake heights',
 'south amboy',
 'spring lake',
 'allentown',
 'belmar',
 'flemington',
 'asbury park',
 'loch arbour village',
 'deal',
 'freehold',
 'millstone',
 'ewing',
 'shrewsbury',
 'cranbury',
 'little silver',
 'rumson',
 'red bank',
 'rocky hill',
 'highlands',
 'matawan',
 'milltown',
 'old bridge',
 'south river',
 'montgomery',
 'north brunswick',
 'manville',
 'south bound brook',
 'milford',
 'somerville',
 'bound brook',
 'raritan',
 'middlesex',
 'dunellen',
 'south plainfield',
 'fanwood',
 'winfield',
 'roselle',
 'bloomsbury',
 'cranford',
 'westfield town',
 'north caldwell',
 'west new york town',
 'elizabeth',
 'mountainside',
 'phillipsburg town',
 'new providence',
 'greenwich',
 'oxford',
 'lopatcong',
 'maplewood',
 'bogota',
 'south orange village',
 'hasbrouck heights',
 'union',
 'city of orange',
 'belleville',
 'essex fells',
 'fairview',
 'glen ridge',
 'roseland',
 'rutherford',
 'hope',
 'fredon',
 'ridgefield',
 'east rutherford',
 'palisades park',
 'wallington',
 'west caldwell',
 'north haledon',
 'harrison town',
 'green',
 'alpine',
 'fort lee',
 'south hackensack',
 'passaic',
 'blairstown',
 'mountain lakes',
 'leonia',
 'little falls',
 'garfield',
 'lodi',
 'prospect park',
 'branchville',
 'englewood cliffs',
 'woodland park',
 'englewood',
 'lafayette',
 'ringwood',
 'hardyston',
 'teaneck',
 'maywood',
 'rochelle park',
 'independence',
 'tenafly',
 'haledon',
 'bergenfield',
 'andover',
 'paterson',
 'allamuchy',
 'glen rock',
 'hawthorne',
 'ho-ho-kus',
 'washington',
 'waldwick',
 'wyckoff',
 'franklin lakes',
 'wanaque',
 'upper saddle river',
 'frankford',
 'franklin',
 'hamburg',
 'sandyston',
 'vernon',
 'irvington',
 'hampton',
 'stillwater',
 'madison',
 'harding',
 'morris plains',
 'victory gardens',
 'randolph',
 'mine hill',
 'rockaway',
 'absecon',
 'pleasantville',
 'egg harbor',
 'manasquan',
 'clifton',
 'netcong',
 'evesham']

In [117]:
muni_names['town_bare'] = t
muni_names.sort_values(by='town_bare')
muni_names['town_bare'][83]

'atlantic'

In [119]:
muni_names['town_bare'][83] = 'atlantic city'
muni_names['town_bare'][83]

'atlantic city'

In [120]:
muni_names['lower_town'] = muni_names['town_bare']

In [130]:
m = muni_names.merge(trains, on=['lower_town','county'], how='outer')

In [132]:
m.head()
m.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 610 entries, 0 to 609
Data columns (total 9 columns):
FIPS          565 non-null object
town          565 non-null object
county        610 non-null object
town_bare     565 non-null object
lower_town    610 non-null object
towns         144 non-null object
munis         144 non-null object
counties      144 non-null float64
vals          144 non-null float64
dtypes: float64(2), object(7)
memory usage: 47.7+ KB

In [133]:
m.to_csv('trainmerge.csv')

In [163]:
import numpy as np
stations = pd.read_csv('njtrain_stations.csv', usecols=[0,3])
stations = stations.fillna(0)
#stations['FIPS'] = stations['FIPS'].to_string()
stations.head()

         FIPS  num_train_stat
0  3402500070             0.0
1  3400100100             1.0
2  3401900550             0.0
3  3404100670             0.0
4  3400300700             1.0

In [168]:
stations['FIPS'] = [str(k) for k in stations['FIPS']]
stations.info()
stations.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 2 columns):
FIPS              565 non-null object
num_train_stat    565 non-null float64
dtypes: float64(1), object(1)
memory usage: 8.9+ KB

         FIPS  num_train_stat
0  3402500070             0.0
1  3400100100             1.0
2  3401900550             0.0
3  3404100670             0.0
4  3400300700             1.0

In [169]:
stations.to_pickle('njtrain_stations.pkl')